### ISSUE TITLE
wrong approch

### ISSUE THREAD

**Issue by sen1** [sahle123/intro-data-capstone-musclehub#1]
https://github.com/sahle123/intro-data-capstone-musclehub/blob/deb54fbf86c335f436d78ce2e07e42968f36b56b/Final_project_Sahal_Alturaigi/musclehub.py#L178-L179

You should `pd.notnull` for checking `null` values. Manually checking for `None` is much less efficient because there are also missing data which are stored as `Null`. Another point is to use the pandas series. See below, there is no `axis=1` argument.
```
df['ab_test_group'] = df.fitness_test_date.apply(lambda x:
                                                'A' if pd.notnull(x) else 'B')
```

**Comment by sahle123** [comment]
I think for some of my later conditional statements I started using the pd.isnull() or pd.notnull() methods. I remember having an issue with the `None` keyword in the database because it worked little differently from `Null`. 

I'll be sure to update my code.
