### ISSUE TITLE
Easier methods

### ISSUE THREAD

**Issue by sen1** [sahle123/intro-data-capstone-musclehub#2]
https://github.com/sahle123/intro-data-capstone-musclehub/blob/deb54fbf86c335f436d78ce2e07e42968f36b56b/Final_project_Sahal_Alturaigi/musclehub.py#L268-L277

That works and good job. However much less efficient. I would do:
```
app_pivot['Total'] = app_pivot.Application + app_pivot['No Application']
app_pivot['Percent with Application'] = app_pivot.Application / app_pivot.Total
```

You dont need the apply function while creating a simple new column out of existing columns.

**Comment by sahle123** [comment]
I do have a bad habit of opting for imperative programming styles since, to me, they're easier to understand.
