### ISSUE TITLE
Wrong test

### ISSUE THREAD

**Issue by sen1** [sahle123/intro-data-capstone-musclehub#3]
https://github.com/sahle123/intro-data-capstone-musclehub/blob/deb54fbf86c335f436d78ce2e07e42968f36b56b/Final_project_Sahal_Alturaigi/musclehub.py#L298

Binomial test is useful when you are comparing from a single group. You are testing group B values with probability from group A. hmmm!!! thats tricker. It may work!

However, the best test would be a chisquare test. chisquare test compares categorical values from multiple groups. 
```
from scipy.stats import chi2_contingency

contingency = [[250, 2254], [325, 2175]]
chi2_contingency(contingency)
```

**Comment by sahle123** [comment]
In the future, should I avoid using binomial tests when comparing to separate groups of data?
