### ISSUE TITLE
Add line breaks to increase code readability

### ISSUE THREAD

**Issue by sen1** [sahle123/intro-data-capstone-musclehub#4]
https://github.com/sahle123/intro-data-capstone-musclehub/blob/deb54fbf86c335f436d78ce2e07e42968f36b56b/Final_project_Sahal_Alturaigi/musclehub.py#L384

I would add line breaks to increase code readability. Code styling is not something we followed in this course. However, it is very important. 
```
member_pivot = member_count.pivot(columns='is_member',
                                  index='ab_test_group',
                                  values='first_name')\
                           .reset_index()
```

Read the PEP8 guide for the maximum length of a code line:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by sahle123** [comment]
I'll fix that up too
