### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [sahle123/intro-data-capstone-musclehub#5]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your Python work was good. There are a couple points where your code could be accomplished a bit more efficiently, but everything worked the way it was supposed to.

Presentation: I think your graphs look excellent. Really liked your conclusions were succinct and on point, so great work there. I was wondering if the Binomial test would predict the same thing as Chisquare test. It would. As you have shown beautifully. Great job. 

Liked your flow diagram as well. 

Excellent work overall. 100/100 👏

**Comment by sahle123** [comment]
Thanks for all of the feedback! I really enjoyed the course too!

Is there anything else that I need to do for the course?
